name: TEST

on:
  # トリガーとなるイベントを定義
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

  workflow_dispatch:

# 実行するジョブを定義
jobs:
  # 任意のジョブ名を定義
  test:
    # 実行環境を指定
    runs-on: ubuntu-latest

    # ステップごとの区分け
    steps:
      - uses: actions/checkout@v2

      # 任意の実行名、実行コマンドを記載
      - name: run test
        run: echo "test"

      - name: env test
        run: echo "TEST_KEY=" > test.txt

      - name: env test2
        env: SUPER_SECRET:${{ secrets.TEST_KEY }}
        run: sed -r -i "s/^TEST_KEY=$/TEST_KEY=$SUPER_SECRET/"  test.txt

      - name: env test3
        run: cat  test.txt
